# Install the required libraries
!pip install -q openai
!pip install -q progpt

# Import the Generative class from ProGPT library
from ProGPT import Generative

# Get your Access token here - https://chat.openai.com/api/auth/session
# Replace 'your_access_token' with your actual OpenAI API access token
access_token = 'your_access_token'
bot = Generative(access_token)

# Prompt ChatGPT with a question
print(bot.prompt("who owns apple?"))

import os
import subprocess

# Function to read a text file, display the first 50 words, and interact with ChatGPT
def read_text_file(file_path, num_words=50):
    try:
        # Open the specified text file
        with open(file_path, 'r') as file:
            # Read the entire content of the file
            content = file.read()
            print("File Contents:")
            
            # Display the first 50 words
            first_50_words = ' '.join(content.split()[:num_words])
            print(first_50_words)

            # Prompt ChatGPT with the first 50 words
            chatgpt_output = bot.prompt(first_50_words + " Is this generated by you")
            print("\nChatGPT Output:")
            print(chatgpt_output)

    except FileNotFoundError:
        print(f"File not found at path: {file_path}")
    except Exception as e:
        print(f"An error occurred: {e}")

# Main function to execute the script
def main():
    # Construct the full path to the text file
    file_path = os.path.join("/content/trojan_test.txt")

    # Read and display the contents of the text file
    read_text_file(file_path)

# Entry point of the script
if __name__ == "__main__":
    main()
