

# Import necessary libraries
import streamlit as st
from ProGPT import Generative

# Get your Access token here - https://chat.openai.com/api/auth/session
# Replace 'your_access_token' with your actual OpenAI API access token
access_token = "xxxx"
bot = Generative(access_token)

# Function to read a text file, display the first 50 words, and interact with ChatGPT
def read_text_file(uploaded_file, num_words=50):
    try:
        # Read the entire content of the uploaded file as bytes
        content = uploaded_file.read()
        st.subheader("File Contents:")

        # Convert the content to a string using str()
        content_str = str(content, 'utf-8')

        # Display the first 50 words
        first_50_words = ' '.join(content_str.split()[:num_words])
        st.write(first_50_words)

        # Prompt ChatGPT with the first 50 words
        chatgpt_output = bot.prompt(first_50_words + " Is this generated by you")
        st.subheader("ChatGPT Output:")
        st.write(chatgpt_output)

    except Exception as e:
        st.error(f"An error occurred: {e}")

# Main function to execute the Streamlit app
def main():
    # Set Streamlit app title
    st.title("Agent Trojan")

    # Allow user to upload a text file
    uploaded_file = st.file_uploader("Choose a text file", type=["txt"])

    # Check if a file is uploaded
    if uploaded_file is not None:
        # Read and display the contents of the uploaded text file
        read_text_file(uploaded_file)

# Entry point of the Streamlit app
if __name__ == "__main__":
    main()